spring:
  application:
    name: java-development-playground
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

app-playground:
  scrapper:
    url-tasas-chile: https://tasas.cmfchile.cl/sbifweb/servlet/InfoFinanciera?indice=4.2.1&FECHA=03/03/2024
